spring.application.name=TTproject

spring.datasource.url=jdbc:postgresql://dpg-d6g0edrh46gs738loh70-a.oregon-postgres.render.com:5432/ttproject
spring.datasource.username=ttproject_user
spring.datasource.password=38aYnuR01GdpmQWe9QmNwe6x0atKHRxV
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true